#!/bin/sh
echo "Setting environment variables for Terraform"
export ARM_SUBSCRIPTION_ID=f86cXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
export ARM_CLIENT_ID=b12cXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
export ARM_CLIENT_SECRET=d1b7XXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
export ARM_TENANT_ID=72f9XXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

