apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-web-v2
  labels:
    app: content-web-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-web-v2
  template:
    metadata:
      labels:
        app: content-web-v2
    spec:
      containers:
      - name: content-web
        image: whatthehackmsft/content-web:v2
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env:
        - name: CONTENT_API_URL
          value: "http://content-api:3001"