apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysqld
  namespace: "{{ .Values.infrastructure.namespace }}"
data:
  mysql_default_user: {{ .Values.infrastructure.username | b64enc }}
  mysql_password: {{ .Values.infrastructure.password | b64enc }}