
// Publish speeding violation
POST http://127.0.0.1:6001/collectfine
Content-Type: application/json

{ "vehicleId": "RT-318-K", "roadId": "A12", "violationInKmh": 15, "timestamp": "2020-09-20T08:33:41" }
