
# You will need to install the following VSCode extension: humao.rest-client

# Please click on the "Send Request" option above each URL to transmit the request to the backend

# This will allow you to test your function endpoint to make sure they are ready to be intergrated with the frontend

@api_endpoint = http://localhost:7072
@conversation_id = 22334567
# Make sure that you specify the api_endpoint and conversation_id shared variables in your extension config

# Use this to interact with Donald (Click Send Request)
POST {{api_endpoint}}/api/assistants-ask-donald HTTP/1.1
Content-Type: application/json
x-conversation-id: {{conversation_id}}

{
    "message": "what is your name?"
}


###


# Use this to interact with Callum (Click Send Request)
POST {{api_endpoint}}/api/assistants-ask-callum HTTP/1.1
Content-Type: application/json
x-conversation-id: {{conversation_id}}

{
    "message": "what is your name?"
}


###

# Use this to interact with Veta (Click Send Request)
POST {{api_endpoint}}/api/assistants-ask-veta HTTP/1.1
Content-Type: application/json
x-conversation-id: {{conversation_id}}


{
    "message": "What dates can I make a yacht reservation?"
}

###

# Use this to interact with Priscilla (Click Send Request)
POST {{api_endpoint}}/api/assistants-ask-priscilla HTTP/1.1
Content-Type: application/json
x-conversation-id: {{conversation_id}}


{
    "message": "what is your name?"
}

###

# Use this to interact with Murphy (Click Send Request)
POST {{api_endpoint}}/api/assistants-ask-murphy HTTP/1.1
Content-Type: application/json
x-conversation-id: {{conversation_id}}


{
    "message": "Do I have any exams that were submitted recently?"
}