# These are secrets used to configure the application
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.globalConfig.secretName }}"
  namespace: "{{ .Values.infrastructure.namespace }}"
data:
  app_braintree_merchant_id: {{ .Values.globalConfig.brainTreeMerchantId | b64enc }}
  app_braintree_public_key: {{ .Values.globalConfig.brainTreePublicKey | b64enc }}
  app_braintree_private_key: {{ .Values.globalConfig.brainTreePrivateKey | b64enc }}
  app_recaptcha_public_key: {{ .Values.globalConfig.recaptchaPublicKey | b64enc }}
  app_recaptcha_private_key: {{ .Values.globalConfig.recaptchaPrivateKey | b64enc }}
  app_datasource_url: {{ .Values.appConfig.dataSourceURL | b64enc }}
  app_datasource_username: {{ .Values.appConfig.dataSourceUser | b64enc }}
  app_datasource_password: {{ .Values.appConfig.dataSourcePassword | b64enc }}
