kind: Service
apiVersion: v1
metadata:
  name: vehicle-registration-service 
  labels:
    app: vehicle-registration-service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3500
  selector:
    app: vehicle-registration-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-registration-service
  labels:
    app: vehicle-registration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-registration-service
  template:
    metadata:
      labels:
        app: vehicle-registration-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "vehicleregistrationservice"
        dapr.io/app-port: "6002"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-cpu-request: "100m"
        dapr.io/sidecar-memory-request: "250Mi"
        dapr.io/sidecar-cpu-limit: "300m"
        dapr.io/sidecar-memory-limit: "1000Mi"
        dapr.io/config: "zipkin"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: vehicle-registration-service
        image: crdaprusscdemo.azurecr.io/vehicleregistrationservice:assignment08
        ports:
        - containerPort: 6002
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6002
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds : 5
          failureThreshold : 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 6002
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds : 5
          failureThreshold: 3
      imagePullSecrets:
      - name: dapr-acr-pull-secret
