apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres
  namespace: "{{ .Values.infrastructure.namespace }}"
data:
  postgres_default_user: {{ .Values.infrastructure.username | b64enc }}
  postgres_password: {{ .Values.infrastructure.password | b64enc }}