apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oracle
  namespace: "{{ .Values.infrastructure.namespace }}"
data:
  oracle_sid: {{ .Values.infrastructure.sid | b64enc }}
  oracle_pdb: {{ .Values.infrastructure.pdb | b64enc }}
  oracle_pwd: {{ .Values.infrastructure.password | b64enc }}