apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer
  namespace: whatthehack
  labels:
    k8s-app: webapp-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: nginx-webapp