[ClassVersion("1.0.0.0"), FriendlyName("xDnsServerZoneScope")]
class MSFT_xDnsServerZoneScope : OMI_BaseResource
{
    [Key, Description("Specifies the name of the Zone Scope.")] string Name;
    [Key, Description("Specify the existing DNS Zone to add a scope to.")] string ZoneName;
    [Write, Description("Should this DNS Server Zone Scope be present or absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

