{{- $name := include "chat-service-web-api.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ $name }}"
  labels:
    app: {{ template "chat-service-web-api.name" . }}
    chart: {{ template "chat-service-web-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MSCosmosDBOpenAI__OpenAI__Endpoint: {{ .Values.openAi.endpoint | b64enc }}
  MSCosmosDBOpenAI__OpenAI__Key: {{ .Values.openAi.key | b64enc }}
  MSCosmosDBOpenAI__CosmosDB__Endpoint: {{ .Values.cosmosDb.endpoint | b64enc }}
  MSCosmosDBOpenAI__CosmosDB__Key: {{ .Values.cosmosDb.key | b64enc }}
  MSCosmosDBOpenAI__DurableSystemPrompt__BlobStorageConnection: {{ .Values.durableSystemPrompt.blobStorageConnection | b64enc }}
  MSCosmosDBOpenAI__BlobStorageMemorySource__ConfigBlobStorageConnection: {{ .Values.blobStorageMemorySource.configBlobStorageConnection | b64enc }}
  ApplicationInsights__ConnectionString: {{ .Values.applicationInsights.connectionString | b64enc }}