name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Step one
      run: echo "Log from step one"
    - name: Step two
      run: echo "Log from step two"
      
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Cowsays
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'Moo!'
        color: 'red'