apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
    aadpodidentitybinding: app1-identity
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - image: hack6180.azurecr.io/hack/sqlapi:1.0
        name: api
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SQL_SERVER_PASSWORD
          value: "Microsoft123!"
        - name: SQL_SERVER_USERNAME
          value: "azure"
        - name: SQL_SERVER_FQDN
          value: "hack6180.database.windows.net"
        - name: SQL_ENGINE
          value: "sqlserver"
        - name: USE_SSL
          value: "yes"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: api
