
RENAME OBJECT [FACTCURRENCYRATE] TO [FACTCURRENCYRATE_OLD]
GO

CREATE TABLE [DBO].[FACTCURRENCYRATE]
(
	[CURRENCYKEY] [INT] NOT NULL,
	[DATEKEY] [INT] NOT NULL,
	[AVERAGERATE] [FLOAT] NOT NULL,
	[ENDOFDAYRATE] [FLOAT] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [CURRENCYKEY] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO


INSERT INTO [FACTCURRENCYRATE]
SELECT C.CURRENCYKEY
	, D.DATEKEY
	, ABS(CHECKSUM(NEWID())) % 0.123456 AVERAGERATE
	, ABS(CHECKSUM(NEWID())) % 0.123456 ENDOFDAYRATE 
FROM DIMDATE D, DIMCURRENCY C
GO