RENAME OBJECT [DIMACCOUNT] TO [DIMACCOUNT_OLD]
GO

CREATE TABLE [DIMACCOUNT]
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
AS
SELECT * FROM [DIMACCOUNT_OLD]
GO


DELETE FROM DIMACCOUNT WHERE ACCOUNTKEY > 101

DECLARE @MAXACCOUNT INT = (SELECT MAX(ACCOUNTKEY) FROM DIMACCOUNT)

INSERT INTO DIMACCOUNT
SELECT 
	ROW_NUMBER() OVER(ORDER BY ACCOUNTKEY) + @MAXACCOUNT [ACCOUNTKEY]
	, [PARENTACCOUNTKEY]
	, [ACCOUNTCODEALTERNATEKEY]
	, [PARENTACCOUNTCODEALTERNATEKEY]
	, [ACCOUNTTYPE] +  ' ' + [ACCOUNTDESCRIPTION]   [ACCOUNTDESCRIPTION]
	, [ACCOUNTTYPE]
	, [OPERATOR]
	, [CUSTOMMEMBERS]
	, [VALUETYPE]
	, [CUSTOMMEMBEROPTIONS]
FROM DIMACCOUNT WHERE ACCOUNTKEY <= 101
GO 4


DECLARE @MAXACCOUNT INT = (SELECT MAX(ACCOUNTKEY) FROM DIMACCOUNT)

INSERT INTO DIMACCOUNT
SELECT 
	ROW_NUMBER() OVER(ORDER BY ACCOUNTKEY) + @MAXACCOUNT [ACCOUNTKEY]
	, [PARENTACCOUNTKEY]
	, [ACCOUNTCODEALTERNATEKEY]
	, [PARENTACCOUNTCODEALTERNATEKEY]
	, [ACCOUNTDESCRIPTION]  +' ' + [ACCOUNTTYPE]   [ACCOUNTDESCRIPTION]
	, [ACCOUNTTYPE]
	, [OPERATOR]
	, [CUSTOMMEMBERS]
	, [VALUETYPE]
	, [CUSTOMMEMBEROPTIONS]
FROM DIMACCOUNT WHERE ACCOUNTKEY <= 101
GO 4


INSERT INTO [DIMORGANIZATION] VALUES(15,1,1,'ITALY',36)
INSERT INTO [DIMORGANIZATION] VALUES(16,1,1,'AUSTRIA',36)
INSERT INTO [DIMORGANIZATION] VALUES(17,1,1,'SPAIN',36)
INSERT INTO [DIMORGANIZATION] VALUES(18,1,1,'POLAND',36)
INSERT INTO [DIMORGANIZATION] VALUES(19,1,1,'BELGIUM',36)
INSERT INTO [DIMORGANIZATION] VALUES(20,1,1,'NETHERLAND',36)
INSERT INTO [DIMORGANIZATION] VALUES(21,1,1,'LUXENBURG',36)
INSERT INTO [DIMORGANIZATION] VALUES(22,1,1,'PORTUGAL',36)
INSERT INTO [DIMORGANIZATION] VALUES(23,1,1,'WEST EUROPE',36)
INSERT INTO [DIMORGANIZATION] VALUES(24,1,1,'CENTRAL EUROPE',36)
GO


RENAME OBJECT [FACTFINANCE] TO [FACTFINANCE_OLD]
GO


CREATE TABLE [DBO].[FACTFINANCE]
(
	[FINANCEKEY] [INT] NOT NULL,
	[DATEKEY] [INT] NOT NULL,
	[ORGANIZATIONKEY] [INT] NOT NULL,
	[DEPARTMENTGROUPKEY] [INT] NOT NULL,
	[SCENARIOKEY] [INT] NOT NULL,
	[ACCOUNTKEY] [INT] NOT NULL,
	[AMOUNT] [FLOAT] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [FINANCEKEY] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO


INSERT INTO FACTFINANCE
SELECT TOP  321123512
	ROW_NUMBER() OVER(ORDER BY D.DATEKEY) [FINANCEKEY]
	, D.[DATEKEY]
	, O.[ORGANIZATIONKEY]
	, DP.[DEPARTMENTGROUPKEY]
	, S.[SCENARIOKEY]
	, A.[ACCOUNTKEY]
	,  ABS(CHECKSUM(NEWID())) % 3250000 + 1 [AMOUNT]
FROM [DBO].[DIMACCOUNT] A, [DBO].[DIMORGANIZATION] O, DIMDATE D, [DIMDEPARTMENTGROUP] DP, [DBO].DIMSCENARIO S
GO