apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 27017
    targetPort: 27017
  clusterIP: none
  selector:
    name: mongo-db
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name:  mongo-db-sts
  labels:
    name:  mongo-db
spec:
  selector:
    matchLabels:
      name: mongo-db
  serviceName: mongodb
  template:
    metadata:
      labels:
        name:  mongo-db
    spec:
      containers:
      - image:  mongo
        name:  mongo-db-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  27017
          name:  mongo-db
        volumeMounts:
        - mountPath: /data/db
          name: azuredisk-db
        - mountPath: /data/configdb
          name: azuredisk-configdb
      volumes:
        - name: azuredisk-db
          persistentVolumeClaim:
            claimName: <data pvc>
        - name: azuredisk-configdb
          persistentVolumeClaim:
            claimName: <config pvc>