# Default values for eshopaks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "whatthehackmsft/eshoponweb-kubernetes"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# If you run this Helm chart manually, you must insert these values:
connectionStrings:
  catalogConnection: "" 
  identityConnection: "" 
  appInsightsConnection: ""
