drop table account cascade constraint purge;
drop table manager cascade constraint purge;
drop table customer cascade constraint purge;
drop table bakestyle cascade constraint purge;
drop table crust cascade constraint purge;
drop table cutstyle cascade constraint purge;
drop table pizzasize cascade constraint purge;
drop table pizzaside cascade constraint purge;
drop table pizzaitem cascade constraint purge;
drop table ingredient cascade constraint purge;
drop table ingredienttype cascade constraint purge;
drop table pizzaside_pizzaitem cascade constraint purge;
drop table pizza cascade constraint purge;
drop table role cascade constraint purge;
drop table orderevent cascade constraint purge;
drop table customer_deliveryaddresses cascade constraint purge;
drop table tblOrders cascade constraint purge;
drop table deliveryperson cascade constraint purge;
drop table delivery cascade constraint purge;
drop table review cascade constraint purge;
drop table tblorders_orderevent cascade constraint purge;
drop table tblFile cascade constraint purge;
drop table orderitem cascade constraint purge;
drop table review_image cascade constraint purge;
drop table orderitemtemplate cascade constraint purge;
drop table users cascade constraint purge;
drop table orderitemtemplate cascade constraint purge;
drop table HT_CUSTOMER;
drop table HT_DELIVERYPERSON;
drop table HT_MANAGER;
drop table HT_USERS;
drop SEQUENCE PIZZERIA_SEQUENCE;
