apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 27017
    targetPort: 27017
  clusterIP: none
  selector:
    name: mongo-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  mongo-db-deploy
  labels:
    name:  mongo-db
spec:
  selector:
    matchLabels:
      name: mongo-db
  serviceName: mongodb
  template:
    metadata:
      labels:
        name:  mongo-db
    spec:
      containers:
      - image:  mongo
        name:  mongo-db-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  27017
          name:  mongo-db
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-datadisk
        - mountPath: /data/configdb
          name: mongodb-configdisk
      volumes:
        - name: mongodb-datadisk
          persistentVolumeClaim:
            claimName: mongodb-datadisk-pvc
        - name: mongodb-configdisk
          persistentVolumeClaim:
            claimName: mongodb-configdisk-pvc
