apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.userAssignedManagedIdentity.clientId }}
  labels:
    azure.workload.identity/use: "true"
imagePullSecrets:
- name: {{ .Values.imageCredentials.secretName }}