RENAME OBJECT [DIMCUSTOMER] TO [DIMCUSTOMER_OLD]
GO

CREATE TABLE [DBO].[DIMCUSTOMER]
(
	[CUSTOMERKEY] [INT] NOT NULL,
	[GEOGRAPHYKEY] [INT] NULL,
	[CUSTOMERALTERNATEKEY] [NVARCHAR](15) NOT NULL,
	[TITLE] [NVARCHAR](8) NULL,
	[FIRSTNAME] [NVARCHAR](50) NULL,
	[MIDDLENAME] [NVARCHAR](50) NULL,
	[LASTNAME] [NVARCHAR](50) NULL,
	[NAMESTYLE] [BIT] NULL,
	[BIRTHDATE] [DATE] NULL,
	[MARITALSTATUS] [NCHAR](1) NULL,
	[SUFFIX] [NVARCHAR](10) NULL,
	[GENDER] [NVARCHAR](1) NULL,
	[EMAILADDRESS] [NVARCHAR](50) NULL,
	[YEARLYINCOME] [MONEY] NULL,
	[TOTALCHILDREN] [TINYINT] NULL,
	[NUMBERCHILDRENATHOME] [TINYINT] NULL,
	[ENGLISHEDUCATION] [NVARCHAR](40) NULL,
	[SPANISHEDUCATION] [NVARCHAR](40) NULL,
	[FRENCHEDUCATION] [NVARCHAR](40) NULL,
	[ENGLISHOCCUPATION] [NVARCHAR](100) NULL,
	[SPANISHOCCUPATION] [NVARCHAR](100) NULL,
	[FRENCHOCCUPATION] [NVARCHAR](100) NULL,
	[HOUSEOWNERFLAG] [NCHAR](1) NULL,
	[NUMBERCARSOWNED] [TINYINT] NULL,
	[ADDRESSLINE1] [NVARCHAR](120) NULL,
	[ADDRESSLINE2] [NVARCHAR](120) NULL,
	[PHONE] [NVARCHAR](20) NULL,
	[DATEFIRSTPURCHASE] [DATE] NULL,
	[COMMUTEDISTANCE] [NVARCHAR](15) NULL
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
GO


DECLARE @STARTDATE AS DATE = '1950/01/01'
DECLARE @ENDDATE AS DATE = '1995/12/31'
DECLARE @KEY INT = (SELECT MAX(CUSTOMERKEY) FROM [DBO].[DIMCUSTOMER_OLD] )
DECLARE @I TINYINT = 1


WHILE (@I <= 2)
BEGIN

	;WITH CTE1 AS (SELECT ROW_NUMBER() OVER(ORDER BY NEWID()) I, * FROM [DBO].[DIMCUSTOMER_OLD] )
		, CTE2 AS (SELECT ROW_NUMBER() OVER(ORDER BY NEWID()) I, * FROM [DBO].[DIMCUSTOMER_OLD] )
	INSERT INTO [DIMCUSTOMER]
	SELECT @KEY + ROW_NUMBER() OVER(ORDER BY A.CUSTOMERKEY) CUSTOMERKEY
		, ABS(CHECKSUM(NEWID())) % 655 + 1 GEOGRAPHYKEY
		, 'AW000' + CAST(@KEY + ROW_NUMBER() OVER(ORDER BY A.CUSTOMERKEY) AS VARCHAR(25))[CUSTOMERALTERNATEKEY]
		, A.TITLE
		, A.FIRSTNAME
		, A.MIDDLENAME
		, B.LASTNAME
		, A.[NAMESTYLE]
		, DATEADD(DAY, RAND(CHECKSUM(NEWID()))*(1+DATEDIFF(DAY, @STARTDATE, @ENDDATE)),@STARTDATE) [BIRTHDATE]
		, B.[MARITALSTATUS]
		, A.[SUFFIX]
		, A.GENDER
		, B.LASTNAME + '@ADVENTURE-WORKS.COM'
		, ABS(CHECKSUM(NEWID())) % 1325000.00 + 40000 [YEARLYINCOME]
		, B.[TOTALCHILDREN]
		, CASE WHEN B.[TOTALCHILDREN] > B.[NUMBERCHILDRENATHOME] THEN B.[NUMBERCHILDRENATHOME] ELSE B.[TOTALCHILDREN] END [NUMBERCHILDRENATHOME]
		, B.[ENGLISHEDUCATION]
		, B.[SPANISHEDUCATION]
		, B.[FRENCHEDUCATION]
		, A.[ENGLISHOCCUPATION]
		, A.[SPANISHOCCUPATION]
		, A.[FRENCHOCCUPATION]
		, B.[HOUSEOWNERFLAG]
		, ABS(CHECKSUM(NEWID())) % 4 + 0 [NUMBERCARSOWNED]
		, A.[ADDRESSLINE1]
		, A.[ADDRESSLINE2]
		, FORMAT(ABS(CHECKSUM(NEWID())) % 9999999999 + 0,'# (##) ###-###')[PHONE]
		, B.[DATEFIRSTPURCHASE]
		, A.[COMMUTEDISTANCE]
	FROM CTE1 A
		INNER JOIN CTE2 B
			ON A.I = B.I

	SELECT @KEY = (SELECT MAX(RESELLERKEY) FROM [DBO].[DIMRESELLER] )
	SET @I+=1

END