RENAME OBJECT [DIMPRODUCT] TO [DIMPRODUCT_OLD]
GO

CREATE TABLE [DBO].[DIMPRODUCT]
(
	[PRODUCTKEY] [INT] NOT NULL,
	[PRODUCTALTERNATEKEY] [NVARCHAR](25) NULL,
	[PRODUCTSUBCATEGORYKEY] [INT] NULL,
	[WEIGHTUNITMEASURECODE] [NCHAR](3) NULL,
	[SIZEUNITMEASURECODE] [NCHAR](3) NULL,
	[ENGLISHPRODUCTNAME] [NVARCHAR](200) NOT NULL,
	[SPANISHPRODUCTNAME] [NVARCHAR](200) NULL,
	[FRENCHPRODUCTNAME] [NVARCHAR](200) NULL,
	[STANDARDCOST] [MONEY] NULL,
	[FINISHEDGOODSFLAG] [BIT] NOT NULL,
	[COLOR] [NVARCHAR](15) NOT NULL,
	[SAFETYSTOCKLEVEL] [SMALLINT] NULL,
	[REORDERPOINT] [SMALLINT] NULL,
	[LISTPRICE] [MONEY] NULL,
	[SIZE] [NVARCHAR](50) NULL,
	[SIZERANGE] [NVARCHAR](50) NULL,
	[WEIGHT] [FLOAT] NULL,
	[DAYSTOMANUFACTURE] [INT] NULL,
	[PRODUCTLINE] [NCHAR](2) NULL,
	[DEALERPRICE] [MONEY] NULL,
	[CLASS] [NCHAR](2) NULL,
	[STYLE] [NCHAR](2) NULL,
	[MODELNAME] [NVARCHAR](50) NULL,
	[ENGLISHDESCRIPTION] [NVARCHAR](400) NULL,
	[FRENCHDESCRIPTION] [NVARCHAR](400) NULL,
	[CHINESEDESCRIPTION] [NVARCHAR](400) NULL,
	[ARABICDESCRIPTION] [NVARCHAR](400) NULL,
	[HEBREWDESCRIPTION] [NVARCHAR](400) NULL,
	[THAIDESCRIPTION] [NVARCHAR](400) NULL,
	[GERMANDESCRIPTION] [NVARCHAR](400) NULL,
	[JAPANESEDESCRIPTION] [NVARCHAR](400) NULL,
	[TURKISHDESCRIPTION] [NVARCHAR](400) NULL,
	[STARTDATE] [DATETIME] NULL,
	[ENDDATE] [DATETIME] NULL,
	[STATUS] [NVARCHAR](7) NULL
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
GO

DECLARE @I INT = 1
DECLARE @STEPP INT = (SELECT COUNT(*) FROM [DIMPRODUCT_OLD] )--WHERE ENDDATE IS NULL)
DECLARE @MAXDATE DATETIME2 --= (SELECT MAX(ENDDATE) FROM DIMPRODUCT_OLD)
DECLARE @STEPD TINYINT = 7

INSERT INTO [DIMPRODUCT]
SELECT 
	[PRODUCTKEY]
	, [PRODUCTALTERNATEKEY]
	, [PRODUCTSUBCATEGORYKEY]
	, [WEIGHTUNITMEASURECODE]
	, [SIZEUNITMEASURECODE]
	, [ENGLISHPRODUCTNAME] + ' - DISMISSED -  ' + CASE WHEN [ENDDATE] IS NULL THEN CONVERT(CHAR(8),DATEADD(MONTH,@STEPD,[STARTDATE]),112) ELSE CONVERT(CHAR(8),[ENDDATE],112) END [ENGLISHPRODUCTNAME]
	, [SPANISHPRODUCTNAME] + ' - DESPEDIDO - ' + CASE WHEN [ENDDATE] IS NULL THEN CONVERT(CHAR(8),DATEADD(MONTH,@STEPD,[STARTDATE]),112) ELSE CONVERT(CHAR(8),[ENDDATE],112) END [SPANISHPRODUCTNAME]
	, [FRENCHPRODUCTNAME] + ' - CONGÉDIÉ - ' + CASE WHEN [ENDDATE] IS NULL THEN CONVERT(CHAR(8),DATEADD(MONTH,@STEPD,[STARTDATE]),112) ELSE CONVERT(CHAR(8),[ENDDATE],112) END [FRENCHPRODUCTNAME]
	, [STANDARDCOST]
	, [FINISHEDGOODSFLAG]
	, [COLOR]
	, [SAFETYSTOCKLEVEL]
	, [REORDERPOINT] 
	, [LISTPRICE]
	, [SIZE]
	, [SIZERANGE]
	, [WEIGHT]
	, [DAYSTOMANUFACTURE]
	, [PRODUCTLINE]
	, [DEALERPRICE] 
	, [CLASS]
	, [STYLE]
	, [MODELNAME]  + ' MY ' + DATENAME(YEAR, CASE WHEN [ENDDATE] IS NULL THEN DATEADD(MONTH,@STEPD,[STARTDATE]) ELSE [ENDDATE] END)+ ' - ' +DATENAME(MONTH, CASE WHEN [ENDDATE] IS NULL THEN DATEADD(MONTH,@STEPD,[STARTDATE]) ELSE [ENDDATE] END)
	, [ENGLISHDESCRIPTION]
	, [FRENCHDESCRIPTION]
	, [CHINESEDESCRIPTION]
	, [ARABICDESCRIPTION]
	, [HEBREWDESCRIPTION]
	, [THAIDESCRIPTION]
	, [GERMANDESCRIPTION]
	, [JAPANESEDESCRIPTION]
	, [TURKISHDESCRIPTION]
	, [STARTDATE]
	, CASE WHEN [ENDDATE] IS NULL THEN DATEADD(MONTH,@STEPD,[STARTDATE]) ELSE [ENDDATE] END [ENDDATE]
	, NULL [STATUS]
FROM [DIMPRODUCT_OLD]
	--WHERE PRODUCTKEY = 10

SET @MAXDATE = (SELECT MAX(ENDDATE) FROM DIMPRODUCT)

WHILE(DATEADD(MONTH,@STEPD,@MAXDATE)<GETDATE())
BEGIN
	
	INSERT INTO [DIMPRODUCT]
	SELECT ROW_NUMBER() OVER(ORDER BY PRODUCTALTERNATEKEY) + (@STEPP * @I) PRODUCTKEY
	, [PRODUCTALTERNATEKEY] --+ '-' + CAST(ROW_NUMBER() OVER(ORDER BY PRODUCTALTERNATEKEY) + (@STEPP * @I) AS VARCHAR(5))
	, [PRODUCTSUBCATEGORYKEY]
	, [WEIGHTUNITMEASURECODE]
	, [SIZEUNITMEASURECODE]
	, [ENGLISHPRODUCTNAME] + ' - DISMISSED - ' + CONVERT(CHAR(8),DATEADD(MONTH, (@STEPD) * @I, DATEADD(MONTH, @STEPD, STARTDATE)),112)--+CASE WHEN [ENDDATE] IS NULL THEN CONVERT(CHAR(8),DATEADD(MONTH,6,[STARTDATE]),112) ELSE CONVERT(CHAR(8),[ENDDATE],112) END [ENGLISHPRODUCTNAME]
	, [SPANISHPRODUCTNAME] + ' - DESPEDIDO - ' + CONVERT(CHAR(8),DATEADD(MONTH, (@STEPD) * @I, DATEADD(MONTH, @STEPD, STARTDATE)),112)--+ CASE WHEN [ENDDATE] IS NULL THEN CONVERT(CHAR(8),DATEADD(MONTH,6,[STARTDATE]),112) ELSE CONVERT(CHAR(8),[ENDDATE],112) END [SPANISHPRODUCTNAME]
	, [FRENCHPRODUCTNAME] + ' - CONGÉDIÉ - ' + CONVERT(CHAR(8),DATEADD(MONTH, (@STEPD) * @I, DATEADD(MONTH, @STEPD, STARTDATE)),112)--+ CASE WHEN [ENDDATE] IS NULL THEN CONVERT(CHAR(8),DATEADD(MONTH,6,[STARTDATE]),112) ELSE CONVERT(CHAR(8),[ENDDATE],112) END [FRENCHPRODUCTNAME]
	, [STANDARDCOST]
	, [FINISHEDGOODSFLAG]
	, [COLOR]
	, [SAFETYSTOCKLEVEL]
	, [REORDERPOINT] + ABS(CHECKSUM(NEWID())) % 8 + 1
	, [LISTPRICE] + ABS(CHECKSUM(NEWID())) % 101.25 + 1
	, [SIZE]
	, [SIZERANGE]
	, [WEIGHT] - 0.81
	, [DAYSTOMANUFACTURE]
	, [PRODUCTLINE]
	, [DEALERPRICE] + ABS(CHECKSUM(NEWID())) % 145.32 + 1
	, [CLASS]
	, [STYLE]
	, [MODELNAME] + ' MY ' + DATENAME(YEAR, DATEADD(MONTH, @STEPD * @I, STARTDATE))+ ' - ' +DATENAME(MONTH, DATEADD(MONTH, @STEPD * @I, STARTDATE))
	, [ENGLISHDESCRIPTION]
	, [FRENCHDESCRIPTION]
	, [CHINESEDESCRIPTION]
	, [ARABICDESCRIPTION]
	, [HEBREWDESCRIPTION]
	, [THAIDESCRIPTION]
	, [GERMANDESCRIPTION]
	, [JAPANESEDESCRIPTION]
	, [TURKISHDESCRIPTION]
	, DATEADD(MONTH, @STEPD * @I, STARTDATE) [STARTDATE] 
	, DATEADD(MONTH, (@STEPD) * @I, DATEADD(MONTH, @STEPD, STARTDATE)) [ENDDATE] 
	, NULL STATUS
	FROM [DIMPRODUCT_OLD]
		WHERE DATEADD(MONTH,@STEPD * @I,STARTDATE)< GETDATE() AND ENDDATE IS NULL
			--AND PRODUCTKEY = 10
	
	SET @I+=1
	SET @MAXDATE = (SELECT MAX(ENDDATE) FROM DIMPRODUCT)

END

	INSERT INTO [DIMPRODUCT]
	SELECT ROW_NUMBER() OVER(ORDER BY PRODUCTALTERNATEKEY) + (@STEPP * @I) PRODUCTKEY
		, [PRODUCTALTERNATEKEY] --+ '-' + CAST(ROW_NUMBER() OVER(ORDER BY PRODUCTALTERNATEKEY) + (@STEPP * @I) AS VARCHAR(5))
			, [PRODUCTSUBCATEGORYKEY]
	, [WEIGHTUNITMEASURECODE]
	, [SIZEUNITMEASURECODE]
	, [ENGLISHPRODUCTNAME]
	, [SPANISHPRODUCTNAME]
	, [FRENCHPRODUCTNAME]
	, [STANDARDCOST]
	, [FINISHEDGOODSFLAG]
	, [COLOR]
	, [SAFETYSTOCKLEVEL]
	, [REORDERPOINT] + ABS(CHECKSUM(NEWID())) % 8 + 1
	, [LISTPRICE] + ABS(CHECKSUM(NEWID())) % 101.25 + 1
	, [SIZE]
	, [SIZERANGE]
	, [WEIGHT] - 0.81
	, [DAYSTOMANUFACTURE]
	, [PRODUCTLINE]
	, [DEALERPRICE] + ABS(CHECKSUM(NEWID())) % 145.32 + 1
	, [CLASS]
	, [STYLE]
	, [MODELNAME] + ' MY ' + DATENAME(YEAR, DATEADD(MONTH, @STEPD * @I, STARTDATE))+ ' - ' +DATENAME(MONTH, DATEADD(MONTH, @STEPD * @I, STARTDATE))
	, [ENGLISHDESCRIPTION]
	, [FRENCHDESCRIPTION]
	, [CHINESEDESCRIPTION]
	, [ARABICDESCRIPTION]
	, [HEBREWDESCRIPTION]
	, [THAIDESCRIPTION]
	, [GERMANDESCRIPTION]
	, [JAPANESEDESCRIPTION]
	, [TURKISHDESCRIPTION]
	, DATEADD(MONTH, @STEPD * @I, STARTDATE) [STARTDATE] 
	, NULL [ENDDATE] 
	, 'CURRENT' STATUS
	FROM [DIMPRODUCT_OLD]
				WHERE DATEADD(MONTH,@STEPD * @I,STARTDATE)< GETDATE() AND ENDDATE IS NULL
		--WHERE STATUS = 'CURRENT'
					--AND PRODUCTKEY = 10
GO