RENAME OBJECT [DIMRESELLER] TO [DIMRESELLER_OLD]
GO


CREATE TABLE [DBO].[DIMRESELLER]
(
	[RESELLERKEY] [INT] NOT NULL,
	[GEOGRAPHYKEY] [INT] NULL,
	[RESELLERALTERNATEKEY] [NVARCHAR](15) NULL,
	[PHONE] [NVARCHAR](25) NULL,
	[BUSINESSTYPE] [VARCHAR](20) NOT NULL,
	[RESELLERNAME] [NVARCHAR](50) NOT NULL,
	[NUMBEREMPLOYEES] [INT] NULL,
	[ORDERFREQUENCY] [CHAR](1) NULL,
	[ORDERMONTH] [SMALLINT] NULL,
	[FIRSTORDERYEAR] [INT] NULL,
	[LASTORDERYEAR] [INT] NULL,
	[PRODUCTLINE] [NVARCHAR](50) NULL,
	[ADDRESSLINE1] [NVARCHAR](60) NULL,
	[ADDRESSLINE2] [NVARCHAR](60) NULL,
	[ANNUALSALES] [MONEY] NULL,
	[BANKNAME] [NVARCHAR](50) NULL,
	[MINPAYMENTTYPE] [TINYINT] NULL,
	[MINPAYMENTAMOUNT] [MONEY] NULL,
	[ANNUALREVENUE] [MONEY] NULL,
	[YEAROPENED] [INT] NULL
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED COLUMNSTORE INDEX
)
GO

TRUNCATE TABLE DIMRESELLER
GO

INSERT INTO [DIMRESELLER]
SELECT * FROM [DIMRESELLER_OLD]
GO

--DECLARE @STARTDATE AS DATE = '1950/01/01'
--DECLARE @ENDDATE AS DATE = '1995/12/31'
DECLARE @KEY INT = (SELECT MAX(RESELLERKEY) FROM [DBO].[DIMRESELLER_OLD] )
DECLARE @I TINYINT = 1


WHILE (@I <= 10)
BEGIN

	;WITH CTE1 AS (SELECT ROW_NUMBER() OVER(ORDER BY NEWID()) I, * FROM [DBO].[DIMRESELLER_OLD] )
		, CTE2 AS (SELECT ROW_NUMBER() OVER(ORDER BY NEWID()) I, * FROM [DBO].[DIMRESELLER_OLD] )
	INSERT INTO [DIMRESELLER]
	SELECT @KEY + ROW_NUMBER() OVER(ORDER BY A.RESELLERKEY) RESELLERKEY
		, ABS(CHECKSUM(NEWID())) % 655 + 1 GEOGRAPHYKEY
		, 'AW000' + CAST(@KEY + ROW_NUMBER() OVER(ORDER BY A.RESELLERKEY) AS VARCHAR(25))[RESELLERALTERNATEKEY]
		, FORMAT(ABS(CHECKSUM(NEWID())) % 9999999999 + 0,'# (##) ###-###')[PHONE]
		, A.[BUSINESSTYPE]
		, A.RESELLERNAME + ' ' + CAST(ABS(CHECKSUM(NEWID())) % 500 + 1 AS VARCHAR(5))[RESELLERNAME]
		, B.[NUMBEREMPLOYEES]
		, A.[ORDERFREQUENCY]
		, ABS(CHECKSUM(NEWID())) % 12 + 1 [ORDERMONTH]
		, B.[FIRSTORDERYEAR]
		, B.[LASTORDERYEAR]
		, A.[PRODUCTLINE]
		, B.[ADDRESSLINE1]
		, B.[ADDRESSLINE2]
		, ABS(CHECKSUM(NEWID())) % 3250000 + 1 [ANNUALSALES]
		, B.[BANKNAME]
		, A.[MINPAYMENTTYPE]
		, B.[MINPAYMENTAMOUNT]
		, ABS(CHECKSUM(NEWID())) % 1354541 + 1 [ANNUALREVENUE]
		, A.[YEAROPENED]
	FROM CTE1 A
		INNER JOIN CTE2 B
			ON A.I = B.I

	SELECT @KEY = (SELECT MAX(RESELLERKEY) FROM [DBO].[DIMRESELLER] )
	SET @I+=1
END
GO 	