INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (1,'Anchovies','USD 1.00',1, 'anchovies.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (2,'Sausage','USD 1.00',1,'sausage.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (3,'Pepperoni','USD 1.00',1,'pepperoni.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (5,'Chicken','USD 1.00',1,'chicken.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (6,'Meatballs','USD 1.00',1,'meatballs.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (7,'Ham','USD 1.00',1,'ham.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (8,'Steak','USD 1.00',1,'steak.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (9,'Bacon','USD 1.00',1,'bacon.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (10,'Beef','USD 1.00',1,'beef.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (11,'Salami','USD 1.00',1,'salami.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (12,'Spinach','USD 1.00',3,'spinach.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (13,'Mushrooms','USD 1.00',3,'mushrooms.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (14,'Red Onion','USD 1.00',3,'red_onion.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (15,'Onion','USD 1.00',3,'onion.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (16,'Banana Peppers','USD 1.00',3,'banana_peppers.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (17,'Pineapple','USD 1.00',3,'pineapple.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (18,'Jalapeno','USD 1.00',3,'jalapeno.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (19,'Black Olive','USD 1.00',3,'black_olive.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (20,'Green Pepper','USD 1.00',3,'green_pepper.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (21,'Tomatoes','USD 1.00',3,'tomato.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (22,'White Sauce','USD 0.25',4,'white_sauce.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (23,'Classic Red','USD 0.25',4,'classic_red_sauce.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (24,'Sweet Red','USD 0.25',4,'sweet_red_sauce.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (25,'Spicy Red','USD 0.25',4,'spicy_red_sauce.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (26,'Roasted Garlic','USD 1.00',3,'garlic.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (27,'Feta Cheese','USD 1.00',2,'feta.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (28,'Cheddar Cheese','USD 1.00',2,'cheddar.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (29,'Shaved Parmesan','USD 1.00',2,'shaved_parmesan.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (30,'Parmesan','USD 1.00',2,'parmesan.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (31,'Mozzarella','USD 1.00',2,'mozzarella.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (32,'Taco','USD 0.25',4,'taco_sauce.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (33,'Buffalo','USD 0.25',4,'buffalo.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (34,'Pesto','USD 0.25',4,'pesto.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (35,'BBQ','USD 0.25',4,'bbq_sauce.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (36,'Goat','USD 1.00',2,'goat.gif');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (37,'Ricotta','USD 1.00',2,'ricotta.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (38,'Blue','USD 1.00',2,'blue.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (39,'Artichoke','USD 1.00',3,'artichoke.png');
INSERT INTO ingredient (id,name,price,ingredienttype_id,imagefilename) VALUES (40,'Basil','USD 1.00',3,'basil.png');
