---
- hosts: localhost
  connection: local
  tasks:  
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: ansible-rg
        name: WTHVNetAN
        address_prefixes: "10.2.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: ansible-rg
        name: default
        address_prefix: "10.2.1.0/24"
        virtual_network: WTHVNetAN
