#!/bin/bash
# =============================================================================
# Foundry Agents Hack - Azure Infrastructure Deployment Script
# Deploys: Resource Group, Microsoft Foundry Resource & Project, Storage, AI Search
# Each run generates a unique suffix to avoid soft-delete naming conflicts.
# =============================================================================

set -euo pipefail

# --- Generate unique suffix (6 random hex chars) to avoid soft-delete collisions ---
UNIQUE_SUFFIX=$(head -c 3 /dev/urandom | od -An -tx1 | tr -d ' \n')

# --- Configuration (override via environment variables) ---
RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-rg-foundry-agents-hack}"
LOCATION="${AZURE_LOCATION:-swedencentral}"
PREFIX="${RESOURCE_PREFIX:-fndry}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_FILE="${SCRIPT_DIR}/main.bicep"
PARAMS_FILE="${SCRIPT_DIR}/main.bicepparam.json"
RESOURCES_DIR="$(dirname "${SCRIPT_DIR}")"
ENV_FILE="${RESOURCES_DIR}/.env"

echo "============================================="
echo " Foundry Agents Hack - Infrastructure Deploy"
echo "============================================="
echo ""
echo "  Resource Group : ${RESOURCE_GROUP}"
echo "  Location       : ${LOCATION}"
echo "  Prefix         : ${PREFIX}"
echo "  Unique Suffix  : ${UNIQUE_SUFFIX}"
echo ""

# --- Check Azure CLI login ---
echo ">> Checking Azure CLI login status..."
ACCOUNT=$(az account show --query "name" -o tsv 2>/dev/null || true)
if [ -z "${ACCOUNT}" ]; then
  echo "   Not logged in. Running 'az login'..."
  az login
  ACCOUNT=$(az account show --query "name" -o tsv)
fi
echo "   Logged in to subscription: ${ACCOUNT}"
echo ""

# --- Confirm subscription ---
SUB_ID=$(az account show --query "id" -o tsv)
echo "   Subscription ID: ${SUB_ID}"
read -rp "   Continue with this subscription? (y/N): " CONFIRM
if [[ ! "${CONFIRM}" =~ ^[Yy]$ ]]; then
  echo "   Aborted. Use 'az account set --subscription <id>' to switch subscriptions."
  exit 1
fi
echo ""

# --- Register required resource providers ---
echo ">> Registering required resource providers..."
PROVIDERS=("Microsoft.CognitiveServices" "Microsoft.Search" "Microsoft.Storage")
for PROVIDER in "${PROVIDERS[@]}"; do
  STATE=$(az provider show --namespace "${PROVIDER}" --query "registrationState" -o tsv 2>/dev/null || echo "NotRegistered")
  if [ "${STATE}" != "Registered" ]; then
    echo "   Registering ${PROVIDER}..."
    az provider register --namespace "${PROVIDER}" --wait
  else
    echo "   ${PROVIDER} already registered."
  fi
done
echo ""

# --- Deploy Bicep template at subscription scope ---
echo ">> Deploying Bicep template..."
DEPLOYMENT_NAME="foundry-hack-${UNIQUE_SUFFIX}-$(date +%Y%m%d%H%M%S)"
az deployment sub create \
  --name "${DEPLOYMENT_NAME}" \
  --location "${LOCATION}" \
  --template-file "${TEMPLATE_FILE}" \
  --parameters "${PARAMS_FILE}" \
  --parameters resourceGroupName="${RESOURCE_GROUP}" location="${LOCATION}" prefix="${PREFIX}" uniqueSuffix="${UNIQUE_SUFFIX}" \
  --output table

echo ""
echo ">> Deployment complete!"
echo ""

# --- Retrieve deployment outputs ---
echo ">> Retrieving deployment outputs..."
OUTPUTS=$(az deployment sub show --name "${DEPLOYMENT_NAME}" --query "properties.outputs" -o json)

RG_NAME=$(echo "${OUTPUTS}" | python3 -c "import sys,json;print(json.load(sys.stdin)['resourceGroupName']['value'])")
FOUNDRY_RESOURCE_NAME=$(echo "${OUTPUTS}" | python3 -c "import sys,json;print(json.load(sys.stdin)['foundryResourceName']['value'])")
FOUNDRY_ENDPOINT=$(echo "${OUTPUTS}" | python3 -c "import sys,json;print(json.load(sys.stdin)['foundryEndpoint']['value'])")
FOUNDRY_PROJECT_NAME=$(echo "${OUTPUTS}" | python3 -c "import sys,json;print(json.load(sys.stdin)['foundryProjectName']['value'])")
STORAGE_ACCOUNT_NAME=$(echo "${OUTPUTS}" | python3 -c "import sys,json;print(json.load(sys.stdin)['storageAccountName']['value'])")
SEARCH_ENDPOINT=$(echo "${OUTPUTS}" | python3 -c "import sys,json;print(json.load(sys.stdin)['searchServiceEndpoint']['value'])")

# --- Get storage connection string ---
echo ">> Retrieving Storage Account connection string..."
STORAGE_CONN_STRING=$(az storage account show-connection-string \
  --name "${STORAGE_ACCOUNT_NAME}" \
  --resource-group "${RG_NAME}" \
  --query "connectionString" -o tsv 2>/dev/null || echo "")

# --- Generate .env file ---
echo ">> Generating .env file at: ${ENV_FILE}"
cat > "${ENV_FILE}" <<EOF
# =============================================================================
# Foundry Agents Hack - Environment Variables (auto-generated by deploy.sh)
# =============================================================================

# --- Azure Subscription & Resource Group ---
AZURE_SUBSCRIPTION_ID=${SUB_ID}
AZURE_RESOURCE_GROUP=${RG_NAME}
AZURE_LOCATION=${LOCATION}

# --- Microsoft Foundry ---
AZURE_AI_FOUNDRY_RESOURCE_NAME=${FOUNDRY_RESOURCE_NAME}
AZURE_AI_FOUNDRY_ENDPOINT=${FOUNDRY_ENDPOINT}
AZURE_AI_PROJECT_NAME=${FOUNDRY_PROJECT_NAME}

# --- Model Deployment ---
AZURE_OPENAI_DEPLOYMENT_NAME=gpt-5.1
AZURE_OPENAI_API_VERSION=2025-01-01-preview

# --- Azure AI Search ---
AZURE_SEARCH_ENDPOINT=${SEARCH_ENDPOINT}
AZURE_SEARCH_INDEX_NAME=

# --- Azure Storage ---
AZURE_STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
AZURE_STORAGE_CONNECTION_STRING=${STORAGE_CONN_STRING}
EOF

echo ""
echo "============================================="
echo " Deployment Summary"
echo "============================================="
echo "  Resource Group     : ${RG_NAME}"
echo "  Foundry Resource   : ${FOUNDRY_RESOURCE_NAME}"
echo "  Foundry Endpoint   : ${FOUNDRY_ENDPOINT}"
echo "  Foundry Project    : ${FOUNDRY_PROJECT_NAME}"
echo "  Storage Account    : ${STORAGE_ACCOUNT_NAME}"
echo "  Search Endpoint    : ${SEARCH_ENDPOINT}"
echo ""
echo "  .env file created  : ${ENV_FILE}"
echo ""
echo " Next Steps:"
echo "   1. Install Python dependencies: pip install -r requirements.txt"
echo "   2. (Optional) Set AZURE_SEARCH_INDEX_NAME in .env when ready"
echo "============================================="
