# =============================================================================
# Foundry Agents Hack - Azure Infrastructure Deployment Script (PowerShell)
# Deploys: Resource Group, Microsoft Foundry Resource & Project, Storage, AI Search
# Each run generates a unique suffix to avoid soft-delete naming conflicts.
# =============================================================================

$ErrorActionPreference = "Stop"

# --- Generate unique suffix (6 random hex chars) to avoid soft-delete collisions ---
$UniqueSuffix = -join ((0..5) | ForEach-Object { '{0:x}' -f (Get-Random -Maximum 16) })

# --- Configuration (override via environment variables) ---
$ResourceGroup = if ($env:AZURE_RESOURCE_GROUP) { $env:AZURE_RESOURCE_GROUP } else { "rg-foundry-agents-hack" }
$Location = if ($env:AZURE_LOCATION) { $env:AZURE_LOCATION } else { "swedencentral" }
$Prefix = if ($env:RESOURCE_PREFIX) { $env:RESOURCE_PREFIX } else { "fndry" }

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$TemplateFile = Join-Path $ScriptDir "main.bicep"
$ParamsFile = Join-Path $ScriptDir "main.bicepparam.json"
$ResourcesDir = Split-Path -Parent $ScriptDir
$EnvFile = Join-Path $ResourcesDir ".env"

Write-Host "============================================="
Write-Host " Foundry Agents Hack - Infrastructure Deploy"
Write-Host "============================================="
Write-Host ""
Write-Host "  Resource Group : $ResourceGroup"
Write-Host "  Location       : $Location"
Write-Host "  Prefix         : $Prefix"
Write-Host "  Unique Suffix  : $UniqueSuffix"
Write-Host ""

# --- Check Azure CLI login ---
Write-Host ">> Checking Azure CLI login status..."
try {
    $Account = az account show --query "name" -o tsv 2>$null
}
catch {
    $Account = $null
}

if (-not $Account) {
    Write-Host "   Not logged in. Running 'az login'..."
    az login
    $Account = az account show --query "name" -o tsv
}
Write-Host "   Logged in to subscription: $Account"
Write-Host ""

# --- Confirm subscription ---
$SubId = az account show --query "id" -o tsv
Write-Host "   Subscription ID: $SubId"
$Confirm = Read-Host "   Continue with this subscription? (y/N)"
if ($Confirm -notmatch "^[Yy]$") {
    Write-Host "   Aborted. Use 'az account set --subscription <id>' to switch subscriptions."
    exit 1
}
Write-Host ""

# --- Register required resource providers ---
Write-Host ">> Registering required resource providers..."
$Providers = @("Microsoft.CognitiveServices", "Microsoft.Search", "Microsoft.Storage")
foreach ($Provider in $Providers) {
    $State = az provider show --namespace $Provider --query "registrationState" -o tsv 2>$null
    if ($State -ne "Registered") {
        Write-Host "   Registering $Provider..."
        az provider register --namespace $Provider --wait
    }
    else {
        Write-Host "   $Provider already registered."
    }
}
Write-Host ""

# --- Deploy Bicep template at subscription scope ---
Write-Host ">> Deploying Bicep template..."
$DeploymentName = "foundry-hack-${UniqueSuffix}-$(Get-Date -Format 'yyyyMMddHHmmss')"
az deployment sub create `
    --name $DeploymentName `
    --location $Location `
    --template-file $TemplateFile `
    --parameters $ParamsFile `
    --parameters resourceGroupName=$ResourceGroup location=$Location prefix=$Prefix uniqueSuffix=$UniqueSuffix `
    --output table

if ($LASTEXITCODE -ne 0) {
    Write-Host ">> ERROR: Deployment failed. Please check the errors above."
    exit 1
}

Write-Host ""
Write-Host ">> Deployment complete!"
Write-Host ""

# --- Retrieve deployment outputs ---
Write-Host ">> Retrieving deployment outputs..."
$OutputsJson = az deployment sub show --name $DeploymentName --query "properties.outputs" -o json
$Outputs = $OutputsJson | ConvertFrom-Json

$RgName = $Outputs.resourceGroupName.value
$FoundryResourceName = $Outputs.foundryResourceName.value
$FoundryEndpoint = $Outputs.foundryEndpoint.value
$FoundryProjectName = $Outputs.foundryProjectName.value
$StorageAccountName = $Outputs.storageAccountName.value
$SearchEndpoint = $Outputs.searchServiceEndpoint.value

# --- Get storage connection string ---
Write-Host ">> Retrieving Storage Account connection string..."
$ErrorActionPreference = "Continue"
$StorageConnectionString = az storage account show-connection-string `
    --name $StorageAccountName `
    --resource-group $RgName `
    --query "connectionString" -o tsv 2>&1 | Where-Object { $_ -notmatch "experimental" }
$ErrorActionPreference = "Stop"

# --- Generate .env file ---
Write-Host ">> Generating .env file at: $EnvFile"
@"
# =============================================================================
# Foundry Agents Hack - Environment Variables (auto-generated by deploy.ps1)
# =============================================================================

# --- Azure Subscription & Resource Group ---
AZURE_SUBSCRIPTION_ID=$SubId
AZURE_RESOURCE_GROUP=$RgName
AZURE_LOCATION=$Location

# --- Microsoft Foundry ---
AZURE_AI_FOUNDRY_RESOURCE_NAME=$FoundryResourceName
AZURE_AI_FOUNDRY_ENDPOINT=$FoundryEndpoint
AZURE_AI_PROJECT_NAME=$FoundryProjectName

# --- Model Deployment ---
AZURE_OPENAI_DEPLOYMENT_NAME=gpt-5.1
AZURE_OPENAI_API_VERSION=2025-01-01-preview

# --- Azure AI Search ---
AZURE_SEARCH_ENDPOINT=$SearchEndpoint
AZURE_SEARCH_INDEX_NAME=

# --- Azure Storage ---
AZURE_STORAGE_ACCOUNT_NAME=$StorageAccountName
AZURE_STORAGE_CONNECTION_STRING=$StorageConnectionString
"@ | Set-Content -Path $EnvFile -Encoding UTF8

Write-Host ""
Write-Host "============================================="
Write-Host " Deployment Summary"
Write-Host "============================================="
Write-Host "  Resource Group     : $RgName"
Write-Host "  Foundry Resource   : $FoundryResourceName"
Write-Host "  Foundry Endpoint   : $FoundryEndpoint"
Write-Host "  Foundry Project    : $FoundryProjectName"
Write-Host "  Storage Account    : $StorageAccountName"
Write-Host "  Search Endpoint    : $SearchEndpoint"
Write-Host ""
Write-Host "  .env file created  : $EnvFile"
Write-Host ""
Write-Host " Next Steps:"
Write-Host "   1. Install Python dependencies: pip install -r requirements.txt"
Write-Host "   2. (Optional) Set AZURE_SEARCH_INDEX_NAME in .env when ready"
Write-Host "============================================="
