// <auto-generated />
using InventoryService.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryService.Api.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20181023230148_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventoryService.Api.Models.InventoryItem", b =>
                {
                    b.Property<string>("Sku")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Quantity");

                    b.HasKey("Sku");

                    b.ToTable("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
