apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.daprComponents.secrets.componentName }}
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: {{ .Values.daprComponents.secrets.keyVaultName }}
    - name: azureClientId
      value: {{ .Values.trafficcontrol.userAssignedManagedIdentity.clientId }}
scopes:
  - {{ .Values.trafficcontrol.fineCollectionService.dapr.appId }}
