apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
      usePodIdentity: "false"
      useVMManagedIdentity: "true"
      userAssignedIdentityID:
          {{ .Values.trafficcontrol.userAssignedManagedIdentity.clientId }}
      keyvaultName: {{ .Values.daprComponents.secrets.keyVaultName }}
      objects: |
        array:
          - |
            objectName: finecalculator-licensekey
            objectType: secret              # object types: secret, key, or cert
          - |
            objectName: smtp-username
            objectType: secret              # object types: secret, key, or cert
          - |
            objectName: smtp-password
            objectType: secret              # object types: secret, key, or cert
      tenantId: {{ .Values.tenantId }}
