# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Infrastructure Release
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  jobs:
  - job:
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '***REPLACE WITH YOUR CONNECTION***'
          subscriptionId: '***REPLACE WITH YOUR SUBSCRIPTION***'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'WTH10'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.DefaultWorkingDirectory)/ARM-Templates/container-webapp-template.json'
          overrideParameters: '-webAppName "ahcsawth10webapp-dev" -hostingPlanName "ahcsawth10hostingapp-asp" -appInsightsLocation "Central US" -appInsightsName "ahcsawth10-ai" -sku "S1" -registryName "ahcsawth10cr" -imageName "ahcsawth10image" -registryLocation "Central US" -registrySku "Standard"'
          deploymentMode: 'Incremental'

- stage: QA
  jobs:
  - job:
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '***REPLACE WITH YOUR CONNECTION***'
          subscriptionId: '***REPLACE WITH YOUR SUBSCRIPTION***'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'WTH10'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.DefaultWorkingDirectory)/ARM-Templates/container-webapp-template.json'
          overrideParameters: '-webAppName "ahcsawth10webapp-qa" -hostingPlanName "ahcsawth10hostingapp-asp" -appInsightsLocation "Central US" -appInsightsName "ahcsawth10-ai" -sku "S1" -registryName "ahcsawth10cr" -imageName "ahcsawth10image" -registryLocation "Central US" -registrySku "Standard"'
          deploymentMode: 'Incremental'
          
- stage: Production
  jobs:
  - job:
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '***REPLACE WITH YOUR CONNECTION***'
          subscriptionId: '***REPLACE WITH YOUR SUBSCRIPTION***'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'WTH10'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.DefaultWorkingDirectory)/ARM-Templates/container-webapp-template.json'
          overrideParameters: '-webAppName "ahcsawth10webapp-prod" -hostingPlanName "ahcsawth10hostingapp-asp" -appInsightsLocation "Central US" -appInsightsName "ahcsawth10-ai" -sku "S1" -registryName "ahcsawth10cr" -imageName "ahcsawth10image" -registryLocation "Central US" -registrySku "Standard"'
          deploymentMode: 'Incremental'