name: Build and Push IntrotoAKS Images
on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      CONTENTWEBTAG: larryclaman/content-web
      CONTENTAPITAG: larryclaman/content-api
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push content-web v1
        uses: docker/build-push-action@v2
        id: contentwebv1
        with:
          push: false
          # Build's context is the set of files located in the specified PATH or URL
          context: '001-IntroToKubernetes/Student/Resources/Challenge 1/content-web'
          # Path to the Dockerfile
          file: '001-IntroToKubernetes/Coach/Solutions/Challenge 1/content-web/Dockerfile-solution'
          # List of tags
          tags: ${REGISTRY}/${CONTENTWEBTAG}:v1, ${REGISTRY}/${CONTENTWEBTAG}:latest
          #github-token: # optional, default is ${{ github.token }}