name: Check Markdown Links

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/checklinks.yml'
      - '001-IntroToKubernetes/**'
  
jobs:

  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Markdown Links Check
        uses: umbrelladocs/action-linkinspector@v1
        with:
          reporter: github-pr-review
          fail_level: any
          config_file: .checklinks_config.yml
               
