name: CI

env:
  registryName: devopsreg.azurecr.io
  repositoryName: wth/razorcore
  dockerfilePath: Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

on:
  push:
    branches: [ main ]
    paths:
    - 'Application/**'
    - '.github/workflows/ci.yml'
  workflow_dispatch:
      
jobs:

  build-and-test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj --no-restore --verbosity normal
    - uses: actions/github-script@v6
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
  
  docker-build-and-push:
  
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Azure Container Registry Login
        uses: docker/login-action@v1.9.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ env.registryName }}
          # Username used to log against the Docker registry
          username: ${{ secrets.ACR_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.ACR_PASSWORD }}
          # Log out from the Docker registry at the end of a job
          logout: true

      - name: Docker Build
        run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath

      - name: Docker Push
        run: docker push $registryName/$repositoryName:$tag
      
  deploy-to-dev:
  
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    environment:
      name: dev
      url: https://devopsreg-dev.azurewebsites.net/
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'devopsreg-dev'
          images: ${{secrets.ACR_NAME}}/wth/razorcore:${{github.run_number}}

  deploy-to-test:
  
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment:
      name: test
      url: https://devopsreg-test.azurewebsites.net/
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'devopsreg-test'
        images: ${{secrets.ACR_NAME}}/wth/razorcore:${{github.run_number}}

  deploy-to-prod:
  
    runs-on: ubuntu-latest
    needs: deploy-to-test
    environment:
      name: prod
      url: https://devopsreg-prod.azurewebsites.net/
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'devopsreg-prod'
        images: ${{secrets.ACR_NAME}}/wth/razorcore:${{github.run_number}}
